#+TITLE: GUIDE WEBSCRAPING - FINVIZ
#+AUTHOR: Edgar Huamantla
#+DATE: <2026-04-27 Mon>
#+FILETAGS: :project3:etf:finviz:selenium:

* Discovery
url = "https://finviz.com/screener.ashx?v=181"

** Hurdles

*** Blank web page 
Issue: beautiful soup returned an empty HTML file.
Solution: Use Selenium.

We will use the styled-row, because every element of the ETF table is wrapped with this tag.

**** Interesting Tags

|---------------------+------------|
| <tag>               | info       |
|---------------------+------------|
| data-boxover-ticker | ETF ticker |
|                     |            |

**** Pagination
{'name': 'td | ', 'id': 'screener_pagination', 'content_head': '123456⋯100', ...}


***  SOLUTIONS
we were able to decompose a website based on its functional areas. what we wanted to do was
exploit the HTML tree pattern to see if we could view the website in a way that would remove noise.

what we ended up doing was iterating through different ways to filter out the html tags.
initially we had one tag that we would look for and an ignore list. this then developed into defining
what areas of map could be labeled as. this eliminated the need for an ignore list.

later we decided to see how we could visualize the website in a way that we were able to capture our data
and look at the browser and see if we left anything on the table (as far as scraping goes).

*** Tree Mapping
The HTML's structure naturally lent itself to recursive functions.
We exploited this when visualizing the web page. What we wanted to do is see if we were capturing what we could
from the web page. What we found is that within the table structures, there are about 7 children cells that
represent one etf. some of these cells are noise while others have the data we are looking for.
Because the website dynamically loads some of these data or provides hovering windows it's not neatly structured.
So what we did was refine how we extracted the HTML. We added indexes to the nodes so that we can define an external
schema that can be passed to a func that would handle extracting data.
We added an expected_count, that is optional for debugging. We can anticipate that a user will run this against many webpages and towards
the end the count should be less than what the first page showed.


#+BEGIN_SRC python
   ETF_COLUMN_MAPPING = {
       6: ['price', 'ticker', 'company', 'industry', 'value', 'country'],
       5: ["dividend"],
       7: ["change_pct"]
   }
   first_dataset = aux_funcs.extract_from_tree_map(
         dom_tree_data,
         schema=ETF_COLUMN_MAPPING,
         expected_count=20
     )

   {
       'price': '114.89',
       'ticker': 'A',
       'company': 'Agilent Technologies Inc',
       'industry': 'Diagnostics & Research',
       'value': '32.47B',
       'country': 'USA',
       'dividend': '0.87%',
       'change_pct': '-0.63%'
   }

#+END_SRC

* Implementation

** Getting Data and storing
Our first run to download the html websites took about 1 hour and 15 minutes for about
552 pages.
So what we decided to do instead is to move this full run from the notebook into a python
file. The user will have to download web page data, either a range of pages or a full download.

*** Notebook Changes
After a user has already completed a data download (full or partial). The notebook will require
manual definition of the folder to use. 
